[package]
name = "smoketest"
version = "0.1.0"
edition = "2024"

[features]
default = []

[lints]
workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
logging = { path = "../logging" }
hotki-server = { path = "../hotki-server" }
hotki-engine = { path = "../hotki-engine" }
hotki-protocol = { path = "../hotki-protocol" }
hotki-world = { path = "../hotki-world", features = ["world-mimic"] }
mac-winops = { path = "../mac-winops" }
mac-keycode = { path = "../mac-keycode" }
tokio = { workspace = true, features = ["rt-multi-thread", "time"] }
winit = "0.30"
objc2-app-kit = { version = "0.3.1", features = ["NSScreen", "NSTextField", "NSFont", "libc"] }
objc2-foundation = "0.3.1"
objc2 = "0.6.2"
keymode = { path = "../keymode" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
config = { version = "0.0.1", path = "../config" }
regex = { workspace = true }
permissions = { version = "0.1.0", path = "../permissions" }
thiserror = { workspace = true }
libc = { workspace = true }
parking_lot = "0.12.4"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
once_cell = { workspace = true }
hotki-world-ids = { version = "0.0.1", path = "../hotki-world-ids" }
