[package]
name = "dumpinput"
version.workspace = true
edition.workspace = true
authors.workspace = true

[[bin]]
name = "dumpinput"
path = "src/main.rs"

[dependencies]
eframe = "0.33.3"
egui = "0.33.3"
